#!/usr/bin/env node
/**
 * fix_glossary_corruption.cjs
 * 
 * Fixes systematic corruption in glossary.json where:
 * 1. Plain 'B' was replaced with '\bar{B}' in text/LaTeX fields
 * 2. Already-complemented '\bar{B}' became '\bar{\bar{B}}'
 * 3. Text words with B+vowel were mangled (Bolean, Bnary, Bt, etc.)
 * 
 * Strategy:
 *   Step 1: '\bar{\bar{B}}' → '\bar{B}'  (restore valid complements)
 *   Step 2: '\bar{B}' → 'B'              (remove spurious complements)
 *   Step 3: Fix remaining text word corruptions
 *   Step 4: Delete all 'html' fields (prerender-formulas.js will regenerate)
 */

const fs = require('fs');
const path = require('path');

const glossaryPath = path.join(__dirname, '..', 'story', 'glossary.json');

// Read
const raw = fs.readFileSync(glossaryPath, 'utf-8');
const data = JSON.parse(raw);

let fixCount = 0;

/**
 * Fix a single string value (not an object key).
 */
function fixString(str) {
  if (typeof str !== 'string') return str;
  
  let fixed = str;
  
  // Step 1: Restore double-complemented B back to single complement
  // In JSON-parsed strings: \bar{\bar{B}} → \bar{B}
  fixed = fixed.replace(/\\bar\{\\bar\{B\}\}/g, '\\bar{B}');
  
  // Step 2: Remove spurious complement (plain B was turned into \bar{B})
  // In JSON-parsed strings: \bar{B} → B
  fixed = fixed.replace(/\\bar\{B\}/g, 'B');
  
  // Step 3: Fix remaining text word corruptions (B+vowel stripped)
  // These patterns only apply to text contexts, not LaTeX
  fixed = fixed.replace(/\bBolean\b/g, 'Boolean');
  fixed = fixed.replace(/\bBnary\b/g, 'Binary');
  fixed = fixed.replace(/\bBstab/g, 'Bistab');  // Bistable, Bistability
  fixed = fixed.replace(/\bBt\b/g, 'Bit');
  fixed = fixed.replace(/\bBlow\b/g, 'Below');
  fixed = fixed.replace(/\bBse\b/g, 'Base');
  fixed = fixed.replace(/\bBses\b/g, 'Buses');
  
  if (fixed !== str) fixCount++;
  return fixed;
}

/**
 * Fix object keys that were corrupted.
 */
function fixKey(key) {
  const keyFixes = {
    'Bolean OR': 'Boolean OR',
    'Bolean NOT': 'Boolean NOT',
    'Bstable': 'Bistable',
    'Bnary Counter': 'Binary Counter',
    'Parity Bt': 'Parity Bit'
  };
  return keyFixes[key] || key;
}

/**
 * Recursively process an object, fixing strings and keys.
 * Skip 'html' fields (they'll be regenerated by prerender).
 */
function processValue(value, parentKey) {
  if (typeof value === 'string') {
    return fixString(value);
  }
  if (Array.isArray(value)) {
    return value.map((item, i) => processValue(item, parentKey));
  }
  if (typeof value === 'object' && value !== null) {
    const result = {};
    for (const [key, val] of Object.entries(value)) {
      // Delete html fields — they will be regenerated
      if (key === 'html') continue;
      
      const fixedKey = fixKey(key);
      result[fixedKey] = processValue(val, key);
    }
    return result;
  }
  return value;
}

// Process the entire glossary
const fixed = processValue(data, null);

// Write back
const output = JSON.stringify(fixed, null, 2);
fs.writeFileSync(glossaryPath, output, 'utf-8');

console.log(`✅ Glossary corruption fixed. ${fixCount} string values corrected.`);
console.log('   HTML fields removed (run prerender-formulas.js to regenerate).');
